### ISSUE TITLE
Could we add WIDE1-1,WIDE2-1 path options to command line?

### ISSUE THREAD

**Issue by vortex64** [casebeer/afsk#5]
I believe it is presently hard coded to WIDE2-1.   For use with mobile stations it is recommended to have WIDE1-1,WIDE2 as described  here... http://wa8lmf.net/DigiPaths/NNNN-Digi-Demo.htm.

The reason I mention this is that this code has now found itself being used inside a raspberry pi zero for a low cost mobile APRS tracker as described here..  http://midnightcheese.com/2015/12/super-simple-aprs-position-beacon/

Perhaps default to WIDE2-1 as present but a -m command line to specify mobile use?

**Comment by casebeer** [comment]
Hi, I believe it should be defaulting to `WIDE1-1,WIDE2` already –  see [line 228 of ax25.py](https://github.com/casebeer/afsk/blob/master/afsk/ax25.py#L228). 

If you use the `-v` verbosity flag, you can get a debug output to check the exact packet contents being encoded for you:

```
$ aprs -c xxxx TEST -v -o /dev/null 2>&1 | grep ax25
INFO:afsk.ax25:Sending packet: 'xxxx>APRS,WIDE1-1,WIDE2-1:TEST'
...
```

If you want to change that, use the `-d` or `--digipeaters` flags:

```
$ aprs -c xxxxx -d 'WIDE2-1' TEST
```

All the flags are documented (lightly) via `aprs -h`.

I noticed on the comments of that post you linked there was a bit of confusion about the `--digipeaters` option docs, so I'll update it to clarify a bit. 

Thanks for the report and the links!
